name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install flake8
          flake8 src

      - name: Unit tests
        run: |
          echo "No unit tests yet"

      # Optional: Databricks CLI steps for bundle validate (requires secrets)
      # - name: Install Databricks CLI
      #   run: |
      #     curl -fsSL https://raw.githubusercontent.com/databricks/cli/main/install.sh | sh
      #     databricks -v
      # - name: Configure Databricks Auth (PAT)
      #   env:
      #     DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      #   run: |
      #     databricks auth token --host "$DATABRICKS_HOST" --token "$DATABRICKS_TOKEN" --name ci --output json > /tmp/dab_profile.json
      #     export DATABRICKS_CONFIG_FILE=/tmp/dab_profile.json
      # - name: Validate bundle
      #   run: |
      #     databricks bundle validate -t dev
